name: PlayerRace
version: 1.0.6
main: com.handy.playerrace.PlayerRace
api-version: "1.13"
author: handy
description: 一款有点好用的超自然种族插件
softdepend: [PlaceholderAPI,Citizens]
commands:
  playerrace:
    description: §a超自然种族插件
    aliases: [plr]
permissions:
  playerrace.*:
    description: §a超自然种族插件
    children:
      playerrace.reload: true
      playerrace.setrace: true
      playerrace.gethelpbook: true
  playerrace.reload:
    description: §a重载插件
    default: op
  playerrace.setrace:
    description: §a设置玩家种族
    default: op
  playerrace.gethelpbook:
    description: §a获取玩家种族帮助之书
    default: true