name: PlayerRace
version: 1.3.1
main: com.handy.playerrace.PlayerRace
api-version: 1.13
website: https://handy-git.gitee.io/rice-doc/#/PlayerRace/zh_CN/log
author: handy
description: 一款有点好用的超自然种族插件
softdepend: [ Residence,PlaceholderAPI ]
commands:
  playerrace:
    description: 超自然种族插件
    aliases: [ plr ]
permissions:
  playerrace.*:
    description: 超自然种族插件
    children:
      playerrace.reload: true
      playerrace.setrace: true
      playerrace.gethelpbook: true
      playerrace.getmengborneosoup: true
      playerrace.findcount: true
      playerrace.findrace: true
  playerrace.reload:
    description: 重载插件
    default: op
  playerrace.setrace:
    description: 设置玩家种族
    default: op
  playerrace.gethelpbook:
    description: 获取玩家种族帮助之书
    default: true
  playerrace.getmengborneosoup:
    description: 获取孟婆汤
    default: op
  playerrace.findcount:
    description: 获取对应种族的玩家数量
    default: op
  playerrace.findrace:
    description: 获取玩家的种族
    default: op