name: PlayerRace
version: 1.0.0
main: com.handy.playerrace.PlayerRace
api-version: "1.13"
author: handy
description: 一款有点好用的超自然种族插件
commands:
  playerrace:
    description: §a超自然种族插件
    aliases: [pls]
permissions:
  playerrace.*:
    description: §a超自然种族插件
    children:
      playerrace.reload: true
      playerrace.vip: true
  playerrace.reload:
    description: §a重载插件
    default: op