name: PlayerRace
version: 1.1.2
main: com.handy.playerrace.PlayerRace
api-version: "1.13"
author: handy
description: 一款有点好用的超自然种族插件
softdepends: [PlaceholderAPI,Citizens,Residence]
commands:
  playerrace:
    description: §a超自然种族插件
    aliases: [plr]
permissions:
  playerrace.*:
    description: §a超自然种族插件
    children:
      playerrace.reload: true
      playerrace.setrace: true
      playerrace.gethelpbook: true
      playerrace.getmengborneosoup: true
      playerrace.findcount: true
      playerrace.findrace: true
  playerrace.reload:
    description: §a重载插件
    default: op
  playerrace.setrace:
    description: §a设置玩家种族
    default: op
  playerrace.gethelpbook:
    description: §a获取玩家种族帮助之书
    default: true
  playerrace.getmengborneosoup:
    description: §a获取孟婆汤
    default: op
  playerrace.findcount:
    description: §a获取对应种族的玩家数量
    default: op
  playerrace.findrace:
    description: §a获取玩家的种族
    default: op